#!/bin/bash

mkdir -p ~/.miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/.miniconda/miniconda.sh
bash ~/.miniconda/miniconda.sh -b -u -p ~/.miniconda
rm -rf ~/.miniconda/miniconda.sh
# After installing, initialize your newly-installed Miniconda. The following commands initialize for bash and zsh shells:

#~/.miniconda/bin/conda init bash
#~/.miniconda/bin/conda init zsh
